openai:
  api_key: "your-openai-api-key"

use_gpt4: true

post_processing:
  enable: true
  max_grade_level: 10

seo_optimization:
  keywords:
    - "example keyword 1"
    - "example keyword 2"

output:
  file: "output.txt"

generation:
  iterations: 10

multilingual:
  default_language: "en"

tools:
  calculator:
    enable: true
  web_search:
    enable: true
  fact_check:
    enable: true

memgpt:
  model: "gpt-4"
  context_window: 8192
  preset: "memgpt_chat"
  model_endpoint_type: "openai"
  openai_key: "your-openai-api-key"
  interface_kwargs:
    debug: false
    show_inner_thoughts: true
    show_function_outputs: false
  default_auto_reply: "..."
  skip_verify: false
  auto_save: false
  seed: 42

input:
  file: "input.txt"
